export const INTERESTS_OPTIONS = [
    'Tecnologia & Inovação',
    'Negócios & Carreira',
    'Festas & Shows',
    'Música',
    'Dança',
    'Saúde & Bem-Estar',
    'Gastronomia',
    'Artes & Cultura',
    'Esportes',
    'Educação & Workshops',
    'Networking',
    'Cinema & Teatro',
    'Religião & Espiritualidade',
    'Games & Geek',
    'Jogos Digitais',
    'Sustentabilidade',
    'Animais de Estimação',
    'Literatura',
    'Filosofia'
];
