export const STRINGS = {
    // Erros Gerais
    ERROR_DEFAULT: 'Ocorreu um erro inesperado. Tente novamente mais tarde.',
    ERROR_NETWORK: 'Sua conexão caiu ou está instável. Verifique sua internet e tente novamente.',
    ERROR_TIMEOUT: 'A solicitação demorou muito para responder. Tente novamente.',
    ERROR_UNAUTHORIZED: 'Sua sessão expirou. Por favor, faça login novamente.',

    // Erros de Banco de Dados (Para Debug / Logs Internos)
    LOG_DB_READ: '[Firestore READ Error]',
    LOG_DB_WRITE: '[Firestore WRITE Error]',
    LOG_AUTH: '[Auth Error]',

    // Autenticação
    AUTH_LOGIN_SUCCESS: 'Login efetuado com sucesso!',
    AUTH_REGISTER_SUCCESS: 'Conta criada com sucesso!',
    AUTH_ERROR_EMPTY_FIELDS: 'Por favor, preencha todos os campos.',
    AUTH_ERROR_INVALID_CREDS: 'Email ou senha inválidos.',
    AUTH_ERROR_NICK_EXISTS: 'Esse Nick já está em uso. Por favor, escolha outro.',
    AUTH_ERROR_TERMS: 'Você precisa aceitar os Termos de Uso para continuar.',
    AUTH_ERROR_ACCOUNT_DISABLED: 'Esta conta foi suspensa pela moderação e não pode mais ser acessada. Se você acha que houve engano, fale com o suporte pelo Contato e Feedback.',
    AUTH_ERROR_TOO_MANY_ATTEMPTS: 'Muitas tentativas seguidas. Aguarde alguns minutos antes de tentar entrar novamente.',

    // Eventos
    EVENT_CREATE_SUCCESS: 'Seu evento foi criado e já está disponível para a comunidade!',
    EVENT_CREATE_ERROR: 'Ocorreu um problema ao salvar seu evento.',
    EVENT_CHAT_TITLE: 'Chat do evento',
    EVENT_CHAT_OPEN: 'Abrir chat do evento',
    EVENT_CHAT_HINT: 'Disponível aos participantes até o término. As mensagens serão apagadas depois.',
    EVENT_CHAT_EMPTY: 'Ainda não há mensagens. Combine os detalhes do encontro por aqui.',
    EVENT_CHAT_CLOSED: 'O chat terminou com o evento.',
    EVENT_CHAT_UNAVAILABLE: 'O chat está disponível apenas para participantes confirmados.',
    EVENT_CHAT_LOADING_ERROR: 'Não foi possível carregar o chat. Confira sua conexão e tente novamente.',
    EVENT_CHAT_SEND_ERROR: 'Não foi possível enviar a mensagem. Tente novamente.',
    EVENT_CHAT_PLACEHOLDER: 'Escreva para o grupo...',
    EVENT_CHAT_PARTICIPANT: 'Participante',
    EVENT_CHAT_ORGANIZER: 'Organizador',
    EVENT_CHAT_YOU: 'Você',
    EVENT_CHAT_BACK: 'Voltar ao evento',
    EVENT_CHAT_SEND_ACCESSIBILITY: 'Enviar mensagem ao evento',
    EVENT_CHAT_RETRY: 'Tentar novamente',
    EVENT_CHAT_NOTIFICATIONS_LABEL: 'Avisos deste chat',
    EVENT_CHAT_NOTIFICATIONS_HELP: 'Um aviso por vez, até abrir o chat. Respeita o ajuste geral do Perfil.',
    EVENT_CHAT_NOTIFICATIONS_ERROR: 'Não foi possível salvar a preferência. Tente novamente.',
    EVENT_CHAT_NOTIFICATIONS_RETRY: 'Não foi possível carregar os avisos. Tentar novamente',
    MANUAL_EVENT_CHAT: 'Quem criou ou confirmou presença pode conversar no chat da página do evento. Quando houver mensagens novas, você recebe um aviso por vez; abrir o chat libera o próximo. Desative os avisos só deste grupo na própria tela do chat. O ajuste geral de mensagens fica no Perfil. O chat fecha ao fim do evento e as mensagens são apagadas depois. Toque no nome de alguém para ver o perfil e denunciar, se necessário.',
    EVENT_REQUIRED_FIELDS_HINT: '* Campos obrigatórios',
    EXTERNAL_EVENT_LOCAL_TIME_LABEL: 'horário local do evento',
    EXTERNAL_EVENT_APP_TIME_LABEL: 'No Reunion Hub (horário de São Paulo)',
    EXTERNAL_EVENT_WITH_TIME_NOTE: 'A data e o horário serão sugeridos no formulário, com duração inicial de 2 horas. Ajuste quando e onde o grupo vai se encontrar. Ingressos continuam no evento externo.',
    EXTERNAL_EVENT_WITHOUT_TIME_NOTE: 'A data será sugerida no formulário. Defina os horários e escolha onde o grupo vai se encontrar. Ingressos continuam no evento externo.',
    HOME_TUTORIAL_INTRO_EXTERNAL: 'Esta é sua tela inicial: deslize as três listas. No Explorar, marcadores roxos mostram eventos externos.',
    EXPLORE_TUTORIAL_INTRO: 'Estes ícones mostram o que aparece no mapa. Toque nos marcadores para saber mais.',
    EXPLORE_TUTORIAL_APP_EVENT: 'Eventos criados no Reunion Hub.',
    EXPLORE_TUTORIAL_EXTERNAL_EVENT: 'Pino roxo da Ticketmaster; toque para criar encontro.',
    EXPLORE_TUTORIAL_COMMUNITY_PLACE: 'Locais cadastrados pela comunidade.',
    EXPLORE_TUTORIAL_OSM_PLACE: 'Locais do OpenStreetMap; vêm desligados.',
    EXPLORE_TUTORIAL_GOOGLE_POI: 'Pontos do Google Maps.',
    MANUAL_EXTERNAL_EVENTS: 'O pino roxo marca eventos da Ticketmaster. Toque para ver detalhes ou criar um encontro com data e horário sugeridos. O filtro começa ligado e guarda sua escolha.',
    EXPLORE_FILTER_HINT: 'OSM vem desligado. Seus filtros ficam salvos.',
    EXPLORE_EXTERNAL_FILTER_HINT: 'Roxo: Ticketmaster. OSM vem desligado. Seus filtros ficam salvos.',
    EVENT_DELETE_CONFIRM: 'Tem certeza que deseja apagar este evento?',
    EVENT_DELETE_SUCCESS: 'Evento apagado com sucesso.',
    EVENT_INVITE_NICK_HINT: 'Confira se digitou certo: é o nick (apelido único, ex.: joao_silva), não o nome exibido no perfil.',
    EVENT_INVITE_NICK_INVALID: 'O nick tem de 3 a 20 caracteres: letras, números, ponto, hífen ou sublinhado.',
    EVENT_INVITE_USER_GONE: 'Esta conta não está mais disponível.',
    EVENT_INVITE_EVENT_GONE: 'Este evento não existe mais.',
    EVENT_INVITE_FAILED: 'Não foi possível enviar este convite agora. Tente novamente.',

    // Chat
    CHAT_MESSAGE_BLOCKED: 'Você bloqueou esta pessoa e não pode enviar mensagens para ela.',

    // UI Global
    BTN_RETRY: 'Tentar Novamente',
    BTN_CANCEL: 'Cancelar',
    BTN_CONFIRM: 'Confirmar',
    BTN_BACK: 'Voltar',
    
    // Error Boundary
    BOUNDARY_TITLE: 'Ops! Ocorreu um problema.',
    BOUNDARY_SUBTITLE: 'O aplicativo encontrou um erro inesperado e precisou ser interrompido.',
};
