import { Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';

type ManualModalProps = { visible: boolean; onClose: () => void; isFirstTime?: boolean };
const Step = ({ icon, title, text }: { icon: keyof typeof Ionicons.glyphMap; title: string; text: string }) => <View style={styles.step}><View style={styles.icon}><Ionicons name={icon} size={20} color="#4F46E5" /></View><View style={styles.stepText}><Text style={styles.stepTitle}>{title}</Text><Text style={styles.stepBody}>{text}</Text></View></View>;

export function ManualModal({ visible, onClose }: ManualModalProps) {
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.overlay} edges={['bottom']}><View style={styles.sheet}>
    <View style={styles.header}><Text style={styles.title}>Manual de Uso do App</Text><TouchableOpacity onPress={onClose}><Ionicons name="close" size={26} color="#6B7280" /></TouchableOpacity></View>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
      <Text style={styles.intro}>Use o Reunion Hub para sair de casa com mais segurança e encontrar pessoas por interesses em comum.</Text>
      <Step icon="map-outline" title="Explore o mapa" text="Veja eventos e locais comunitários. Use filtros para escolher categorias e alterne entre mapa e lista." />
      <Step icon="calendar-outline" title="Crie, participe ou convide" text="Informe título, início, término e localização corretos. Você pode convidar pessoas recentes ou buscar pelo nick; o convite não confirma presença automaticamente. Confirme presença somente quando realmente pretender ir." />
      <Step icon="checkmark-done-outline" title="Registre e revise check-ins" text="O check-in fica disponível apenas durante o evento. O organizador que fizer o próprio check-in recebe, ao término, uma lista para confirmar quem compareceu e tem até 2 horas para revisá-la. Se ele não fizer check-in ou não revisar no prazo, as solicitações pendentes válidas são aprovadas automaticamente." />
      <Step icon="star-outline" title="Entenda a reputação" text="Presenças confirmadas geram pontos. Faltas, cancelamentos com participantes e uso indevido podem reduzir a reputação; contas abaixo do nível mínimo de confiança não podem criar eventos nem confirmar presença. As notificações de ganho ou perda explicam o motivo." />
      <Step icon="heart-outline" title="Use Agenda e Favoritos" text="A Agenda tem quatro seções: Agenda, com o calendário dos seus compromissos e sugestões dos próximos dias; Próximos, com a lista do que você confirmou; Histórico; e Favoritos. No calendário, a barra marca compromisso seu e o ponto marca sugestão. Depois de participar e ter o check-in confirmado, você pode favoritar o evento para mantê-lo salvo, repeti-lo se for o criador ou propor uma nova edição ao organizador." />
      <Step icon="repeat-outline" title="Marque seus hábitos" text="Em um local, registre um ou mais dias da semana e os períodos de cada dia. Esses dados ajudam a comunidade; a exibição no seu perfil público é opcional." />
      <Step icon="chatbubbles-outline" title="Converse com responsabilidade" text="Abra o perfil da pessoa pelo menu do chat, bloqueie contatos indesejados e denuncie comportamentos ou eventos suspeitos." />
      <Step icon="shield-checkmark-outline" title="Cuide da sua segurança" text="Prefira locais públicos, confirme detalhes antes de sair, não envie dinheiro ou dados pessoais e saia de qualquer situação desconfortável." />
      <Step icon="person-circle-outline" title="Ajuste sua privacidade" text="A exibição dos lugares frequentados começa ativa. Em Perfil › Privacidade, você pode ocultá-los do seu perfil público quando quiser. A rotina continua visível no próprio local para ajudar pessoas a se encontrarem nos mesmos dias e períodos." />
      <Step icon="notifications-outline" title="Controle notificações e recomendações" text="Push de mensagens e eventos, lembretes locais e recomendações começam ativos e podem ser desligados em Perfil › Notificações. Os lembretes de eventos podem aparecer duas horas antes, no início e no término. Avisos importantes continuam no sino para consulta dentro do app. Recomendações respeitam um intervalo mínimo de três dias e há um lembrete após sete dias sem abrir o app." />
      <Step icon="key-outline" title="Proteja e gerencie sua conta" text="Ao trocar seu nick ou excluir a conta, confirme sua identidade com a senha atual. Em Editar Perfil você também pode alterar a senha; na entrada do app, use Esqueci minha senha para recuperá-la por e-mail. A exclusão da conta e dos dados vinculados é permanente." />
    </ScrollView>
    <TouchableOpacity style={styles.button} onPress={onClose}><Text style={styles.buttonText}>Começar a usar</Text></TouchableOpacity>
  </View></SafeAreaView></Modal>;
}
const styles = StyleSheet.create({ overlay: { flex: 1, backgroundColor: 'rgba(17,24,39,0.55)', justifyContent: 'flex-end' }, sheet: { maxHeight: '88%', backgroundColor: '#FFF', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontSize: 20, fontWeight: '800', color: '#111827' }, content: { paddingTop: 14 }, intro: { fontSize: 14, lineHeight: 20, color: '#4B5563', marginBottom: 16 }, step: { flexDirection: 'row', gap: 12, paddingVertical: 10 }, icon: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#EEF2FF', alignItems: 'center', justifyContent: 'center' }, stepText: { flex: 1 }, stepTitle: { fontSize: 15, fontWeight: '800', color: '#312E81', marginBottom: 3 }, stepBody: { fontSize: 13, lineHeight: 18, color: '#4B5563' }, button: { backgroundColor: '#4F46E5', borderRadius: 14, padding: 15, alignItems: 'center', marginTop: 10 }, buttonText: { color: '#FFF', fontWeight: '800', fontSize: 16 } });
